name: build_docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - graphviz2drawio
  - graphviz[version='>=12']
  - sphinx=9.1.0
  - sphinxcontrib-jquery
  - sphinx-needs=8.1.1
  - pandoc
  - python=3.13.2
