name: Build design document
run-name: ${{ github.actor }} building the Phlex design document 🚀

on:
  push:
    paths:
      - 'doc/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  build-design-document:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/framework-r-d/phlexdoc:2025-05-01

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build LaTeX document
        working-directory: ./doc
        run: |
          dot -c  # because it's weird out of the box
          git config --global --add safe.directory $GITHUB_WORKSPACE
          make latexpdf

      - name: Upload PDF document
        id: upload-pdf-document
        uses: actions/upload-artifact@v4
        with:
          name: phlex-design-pdf
          path: ./doc/build/latex/phlex-design*.pdf
          if-no-files-found: error

      - name: Build HTML document
        working-directory: ./doc
        run: |
          dot -c  # because it's weird out of the box
          git config --global --add safe.directory $GITHUB_WORKSPACE
          SPHINX_EXISTING_PDF=${{ steps.upload-pdf-document.outputs.artifact-url }} make html

      - name: Upload HTML document
        uses: actions/upload-artifact@v4
        with:
          name: phlex-design-html
          path: ./doc/build/html/
          if-no-files-found: error
